### ISSUE TITLE
Unknown emoji

### ISSUE THREAD

**Issue by WydeZ** [DaRealDorseyBro/discord-minigames#16]
When I do !battle <user> it says " Hey <userr>! <Author> wants to battle, do you accept?

Then in the console it says DiscordAPIError: Unknown emoji

How do I fix

**Comment by AadiatAhmed** [comment]
I modified the emojis from the ` `src/battle.js`` which did work

**Comment by WydeZ** [comment]
> I modified the emojis from the ` `src/battle.js`` which did work

Oh ok I changed it to 👍 and 👎 and it worked!
