### ISSUE TITLE
How to use ispy game?

### ISSUE THREAD

**Issue by Ki123ng** [DaRealDorseyBro/discord-minigames#3]
You have surely made a superb package. But I am not getting how to use ispy game. Please help me out.

**Comment by DaRealDorseyBro** [comment]
That makes sense, I have actually just remade it as a class with better documentation (Sorry for getting back to you so late!), do you need help coding it or actually playing the game?

**Comment by DaRealDorseyBro** [comment]
That makes sense, I have actually just remade it as a class with better documentation (Sorry for getting back to you so late!), do you need help coding it or actually playing the game?

**Comment by Ki123ng** [comment]
> That makes sense, I have actually just remade it as a class with better documentation (Sorry for getting back to you so late!), do you need help coding it or actually playing the game?

thanks
