### ISSUE TITLE
An Issue With The Package

### ISSUE THREAD

**Issue by D3OXY** [DaRealDorseyBro/discord-minigames#4]
Some time when we play battle the hp left changes NaN (NotaNumber).
Can You Fix It..

**Comment by DaRealDorseyBro** [comment]
Could you send a screenshot of the issue? Sorry for getting back to you so late aswell!

**Comment by Cinnamonsroll** [comment]
If possible send a screenshot of this happening and the steps which led to it this will help in fixing this error get back as soon as possible
