### ISSUE TITLE
Unknown Emoji

### ISSUE THREAD

**Issue by Laknicek** [DaRealDorseyBro/discord-minigames#9]
i typed kk!battle <mention>

the bot said : Hey @Myuu! @Laknicek has challenged you to a battle, do you accept?

and then idk how to accept the battle, and when i checked my console i saw that :

(node:16) UnhandledPromiseRejectionWarning: DiscordAPIError: Unknown Emoji

**Comment by DaRealDorseyBro** [comment]
Common Issue, It will be fixed soon.

**Comment by DaRealDorseyBro** [comment]
Fixed!
